---
- name: Install required packages
  hosts: localhost
  become: false  # Elevate privileges if required for installation
  vars:
    required_packages:
      - curl
      - tree
  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ required_packages }}"

